# my-httpd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-httpd
  template:
    metadata:
      labels:
        app: my-httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs  # Mount point inside the container
          name: html-volume
      volumes:
      - name: html-volume
        # Your local path containing HTML files
        hostPath:
          path: /Users/tngnolan/TNGTraining/Minikube/my-k8s-config/http/

