apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: test
spec:
  source:
    repoURL: https://github.com/chrisnolanau/my-k8s-configs.git # Replace with your Git repository URL
    targetRevision: HEAD
    path: nginx
  destination:
    server: 'https://127.0.0.1:49673/' # Minikube Kubernetes API server
    namespace: test
  project: default
  syncPolicy:
    automated: {}
